"""Pydantic models for Workflow Graph Studio."""

from app.models.context_pack import (
    ContextPack,
    ContextPackRequest,
    ContextPackResponse,
    ContextResource,
)
from app.models.context_selector import (
    ContextPath,
    ContextPreview,
    ContextPreviewNode,
    ContextPreviewRequest,
    ContextSelector,
    EdgeStep,
    ParseContextSelectorRequest,
    PropertySelector,
    default_context_selector,
)
from app.models.edge import Edge, EdgeCreate
from app.models.endpoint import (
    Endpoint,
    EndpointCreate,
    EndpointExecuteRequest,
    EndpointExecuteResponse,
    EndpointsResponse,
    EndpointUpdate,
)
from app.models.event import Event, EventCreate
from app.models.external_reference import (
    CaptureReason,
    ExternalReference,
    ExternalReferenceCreate,
    ExternalReferenceWithProjection,
    FreshnessSLO,
    NodeExternalRef,
    NodeExternalRefCreate,
    NodeExternalRefWithDetails,
    Projection,
    ProjectionCreate,
    ProjectionUpdate,
    ReferenceRelationship,
    RetrievalMode,
    Snapshot,
    SnapshotCreate,
    VersionType,
)
from app.models.node import Node, NodeCreate, NodeUpdate
from app.models.suggestion import (
    FieldValueSuggestion,
    FieldValueSuggestionContext,
    FieldValueSuggestionOptions,
    FieldValueSuggestionRequest,
    FieldValueSuggestionResponse,
    NodeSuggestion,
    SuggestionContext,
    SuggestionOptions,
    SuggestionRequest,
    SuggestionResponse,
)
from app.models.workflow import (
    EdgeType,
    Field,
    FieldKind,
    FilterableField,
    FilterGroup,
    FilterOperator,
    FilterSchema,
    NodeState,
    NodeType,
    PropertyFilter,
    RelationalFilter,
    RelationPath,
    Rule,
    StateTransition,
    UIHints,
    ViewFilterParams,
    WorkflowDefinition,
)

__all__ = [
    # Endpoints
    "Endpoint",
    "EndpointCreate",
    "EndpointUpdate",
    "EndpointExecuteRequest",
    "EndpointExecuteResponse",
    "EndpointsResponse",
    # Workflow Definition (Schema)
    "WorkflowDefinition",
    "NodeType",
    "EdgeType",
    "Field",
    "FieldKind",
    "NodeState",
    "StateTransition",
    "UIHints",
    "Rule",
    # Filter Models
    "FilterOperator",
    "PropertyFilter",
    "RelationalFilter",
    "FilterGroup",
    "ViewFilterParams",
    "FilterableField",
    "FilterSchema",
    "RelationPath",
    # Instances
    "Node",
    "NodeCreate",
    "NodeUpdate",
    "Edge",
    "EdgeCreate",
    "Event",
    "EventCreate",
    # Node Suggestions
    "SuggestionRequest",
    "SuggestionOptions",
    "NodeSuggestion",
    "SuggestionContext",
    "SuggestionResponse",
    # Field Value Suggestions
    "FieldValueSuggestionRequest",
    "FieldValueSuggestionOptions",
    "FieldValueSuggestion",
    "FieldValueSuggestionContext",
    "FieldValueSuggestionResponse",
    # Context Selection
    "ContextSelector",
    "ContextPath",
    "EdgeStep",
    "PropertySelector",
    "ContextPreview",
    "ContextPreviewNode",
    "ContextPreviewRequest",
    "ParseContextSelectorRequest",
    "default_context_selector",
    # External References (Pointer/Projection/Snapshot)
    "ExternalReference",
    "ExternalReferenceCreate",
    "ExternalReferenceWithProjection",
    "Projection",
    "ProjectionCreate",
    "ProjectionUpdate",
    "Snapshot",
    "SnapshotCreate",
    "NodeExternalRef",
    "NodeExternalRefCreate",
    "NodeExternalRefWithDetails",
    "VersionType",
    "RetrievalMode",
    "ReferenceRelationship",
    "CaptureReason",
    "FreshnessSLO",
    # Context Packs
    "ContextPack",
    "ContextPackRequest",
    "ContextPackResponse",
    "ContextResource",
]
